name: publicacao

on:
  push:
    branches: [master]

jobs:
  publicar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: instalar dependências
        run: python -m pip install --upgrade virtualenv setuptools build pip

      - name: fazer build do app
        run: python -m build

      - name: obter versão
        run: echo "VERSAO=$(grep -Po '\d.\d.\d' gekitai/__version__.py)" >> $GITHUB_ENV
      - name: criar tag
        run: git tag ${{ env.VERSAO }}
      - name: atualizar github com nova tag
        run: git push origin ${{ env.VERSAO }}

      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.VERSAO }}"
          prerelease: false
          title: "${{ env.VERSAO }}"
          files: |
            dist/*
